import { Inter } from "next/font/google";
import "../assets/css/globals.css";
import '@mantine/core/styles.css';
import { ColorSchemeScript } from '@mantine/core';
import { createTheme, MantineProvider } from '@mantine/core';
import Header from "@/assets/components/Header";
import "bootstrap/dist/css/bootstrap.css"
import "@fortawesome/react-fontawesome";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <head>
            <script src="https://kit.fontawesome.com/11a07c492f.js" crossOrigin="anonymous"></script>
            <title>My awesome title</title>
            <ColorSchemeScript />
        </head>
        <body className={inter.className}>
            <MantineProvider defaultColorScheme="dark">
                <Header></Header>
                {children}
            </MantineProvider>
        </body>
    </html>
  );
}
